# Generated by Django 5.2.8 on 2025-11-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
