# Generated by Django 5.2.8 on 2025-12-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/profile_picture.png', null=True, upload_to='media/avatars/'),
        ),
    ]
