# Generated by Django 5.2.8 on 2025-12-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_facebook_profile_followers_profile_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='follower',
        ),
    ]
