# Generated by Django 5.0.9 on 2025-11-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
